export const EngineList:any = [
  {
    label: "bilibili",
    key: "https://search.bilibili.com/all?keyword=",
    placeholder: "哔哩哔哩 (゜-゜)つロ 干杯~",
    img: "search_enging_img/bilibili.svg",
    name: "bl",
  },
  {
    label: "Google",
    key: "https://www.google.com/search?q=",
    placeholder: "Google搜索",
    img: "search_enging_img/google.svg",
    name: "gg",
  },
  {
    label: "CSDN",
    key: "https://so.csdn.net/so/search?q=",
    placeholder: "CSDN - 专业开发者社区",
    img: "search_enging_img/csdn.svg",
    name: "csdn",
  },
  {
    label: "百度",
    key: "https://www.baidu.com/s?wd=",
    img: "search_enging_img/baidu.svg",
    placeholder: "百度一下，你就知道！",
    name: "bd",
  },
  {
    label: "搜狗",
    key: "https://www.sogou.com/web?query=",
    img: "search_enging_img/sougou.svg",
    placeholder: "搜狗搜索",
    name: "sg",
  },
  {
    label: "必应",
    key: "https://cn.bing.com/search?q=",
    img: "search_enging_img/bing.png",
    placeholder: "必应搜索",
    name: "by",
  },
  {
    label: "知乎",
    key: "https://www.zhihu.com/search?q=",
    img: "search_enging_img/zhihu.svg",
    placeholder: "有问题，上知乎",
    name: "zh",
  },
  {
    label: "微博",
    key: "https://s.weibo.com/weibo?q=",
    placeholder: "随时随地发现新鲜事！",
    img: "search_enging_img/weibo.svg",
    name: "wb",
  },
  {
    label: "豆瓣",
    key: "https://www.douban.com/search?q=",
    placeholder: "提供图书、电影、音乐唱片的推荐 ",
    img: "search_enging_img/douban.svg",
    name: "db",
  },
];
