export const WallpaerList: any = [
  { img: "/bg_img/Cartoon_01.png" },
  { img: "/bg_img/Cartoon_02.png" },
  { img: "/bg_img/Cartoon_03.png" },
  { img: "/bg_img/Cartoon_04.png" },
  { img: "/bg_img/Cartoon_05.png" },
  { img: "/bg_img/Cartoon_06.png" },
  { img: "/bg_img/Cartoon_07.png" },
  { img: "/bg_img/Cartoon_08.png" },
  { img: "/bg_img/Cartoon_09.png" },
  { img: "/bg_img/Cartoon_10.png" },
  { img: "/bg_img/Cartoon_11.png" },
  { img: "/bg_img/Cartoon_12.png" },
  { img: "/bg_img/Cartoon_13.png" },
  { img: "/bg_img/Cartoon_14.png" },
  { img: "/bg_img/Cartoon_15.png" },
  { img: "/bg_img/Cartoon_16.png" },
  { img: "/bg_img/Cartoon_17.png" },
  { img: "/bg_img/Cartoon_18.png" },
  { img: "/bg_img/Cartoon_19.png" },
  { img: "/bg_img/Cartoon_20.png" },
  { img: "/bg_img/Cartoon_21.png" },
  { img: "/bg_img/Cartoon_22.png" },
  { img: "/bg_img/Cartoon_23.png" },
  { img: "/bg_img/Cartoon_24.png" },
];
